DROP SCHEMA IF EXISTS auth CASCADE;

CREATE SCHEMA IF NOT EXISTS auth;

SET SCHEMA 'auth';

/************************************************/
/* USERS  */
/************************************************/
CREATE TABLE USERS
(
   USERNAME  VARCHAR(50)    NOT NULL,
   PASSWORD  VARCHAR(500)   NOT NULL,
   ENABLED   BOOLEAN        NOT NULL
);

ALTER TABLE USERS
   ADD PRIMARY KEY (USERNAME);

/************************************************/
/* AUTHORITIES  */
/************************************************/

CREATE TABLE AUTHORITIES
(
   USERNAME   VARCHAR(50)   NOT NULL,
   AUTHORITY  VARCHAR(50)   NOT NULL
);

ALTER TABLE AUTHORITIES
  ADD CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY (USERNAME)
  REFERENCES USERS (USERNAME)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

CREATE UNIQUE INDEX IX_AUTH_USERNAME
   ON AUTHORITIES (USERNAME ASC, AUTHORITY ASC);

CREATE INDEX FK_AUTHORITIES_USERS_INDEX_A
   ON AUTHORITIES (USERNAME ASC);
